# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\"N\n\rSignupRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"(\n\nOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x19\n\nUIDRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"P\n\x14UpdateProfileRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2\x8c\x02\n\x0bUserService\x12#\n\x06signup\x12\x0e.SignupRequest\x1a\t.Response\x12!\n\x05login\x12\r.LoginRequest\x1a\t.Response\x12$\n\nverify_otp\x12\x0b.OTPRequest\x1a\t.Response\x12*\n\x0ereset_password\x12\r.EmailRequest\x1a\t.Response\x12*\n\x10get_user_profile\x12\x0b.UIDRequest\x1a\t.Response\x12\x37\n\x13update_user_profile\x12\x15.UpdateProfileRequest\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPREQUEST']._serialized_start=23
  _globals['_SIGNUPREQUEST']._serialized_end=101
  _globals['_LOGINREQUEST']._serialized_start=103
  _globals['_LOGINREQUEST']._serialized_end=150
  _globals['_OTPREQUEST']._serialized_start=152
  _globals['_OTPREQUEST']._serialized_end=192
  _globals['_EMAILREQUEST']._serialized_start=194
  _globals['_EMAILREQUEST']._serialized_end=223
  _globals['_UIDREQUEST']._serialized_start=225
  _globals['_UIDREQUEST']._serialized_end=250
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=252
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=332
  _globals['_RESPONSE']._serialized_start=334
  _globals['_RESPONSE']._serialized_end=360
  _globals['_USERSERVICE']._serialized_start=363
  _globals['_USERSERVICE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
