# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.signup = channel.unary_unary(
                '/UserService/signup',
                request_serializer=cloudsecurity__pb2.SignupRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.login = channel.unary_unary(
                '/UserService/login',
                request_serializer=cloudsecurity__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.verify_otp = channel.unary_unary(
                '/UserService/verify_otp',
                request_serializer=cloudsecurity__pb2.OTPRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.reset_password = channel.unary_unary(
                '/UserService/reset_password',
                request_serializer=cloudsecurity__pb2.EmailRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.get_user_profile = channel.unary_unary(
                '/UserService/get_user_profile',
                request_serializer=cloudsecurity__pb2.UIDRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)
        self.update_user_profile = channel.unary_unary(
                '/UserService/update_user_profile',
                request_serializer=cloudsecurity__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.Response.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User Service Definition
    """

    def signup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verify_otp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_user_profile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_user_profile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'signup': grpc.unary_unary_rpc_method_handler(
                    servicer.signup,
                    request_deserializer=cloudsecurity__pb2.SignupRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=cloudsecurity__pb2.LoginRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'verify_otp': grpc.unary_unary_rpc_method_handler(
                    servicer.verify_otp,
                    request_deserializer=cloudsecurity__pb2.OTPRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'reset_password': grpc.unary_unary_rpc_method_handler(
                    servicer.reset_password,
                    request_deserializer=cloudsecurity__pb2.EmailRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'get_user_profile': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_profile,
                    request_deserializer=cloudsecurity__pb2.UIDRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
            'update_user_profile': grpc.unary_unary_rpc_method_handler(
                    servicer.update_user_profile,
                    request_deserializer=cloudsecurity__pb2.UpdateProfileRequest.FromString,
                    response_serializer=cloudsecurity__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Service Definition
    """

    @staticmethod
    def signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/signup',
            cloudsecurity__pb2.SignupRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/login',
            cloudsecurity__pb2.LoginRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def verify_otp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/verify_otp',
            cloudsecurity__pb2.OTPRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reset_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/reset_password',
            cloudsecurity__pb2.EmailRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_user_profile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/get_user_profile',
            cloudsecurity__pb2.UIDRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_user_profile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/update_user_profile',
            cloudsecurity__pb2.UpdateProfileRequest.SerializeToString,
            cloudsecurity__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
