# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\x12\x05\x63loud\"N\n\rSignupRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"(\n\nOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x19\n\nUIDRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"P\n\x14UpdateProfileRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2\xd4\x02\n\x0bUserService\x12/\n\x06signup\x12\x14.cloud.SignupRequest\x1a\x0f.cloud.Response\x12-\n\x05login\x12\x13.cloud.LoginRequest\x1a\x0f.cloud.Response\x12\x30\n\nverify_otp\x12\x11.cloud.OTPRequest\x1a\x0f.cloud.Response\x12\x36\n\x0ereset_password\x12\x13.cloud.EmailRequest\x1a\x0f.cloud.Response\x12\x36\n\x10get_user_profile\x12\x11.cloud.UIDRequest\x1a\x0f.cloud.Response\x12\x43\n\x13update_user_profile\x12\x1b.cloud.UpdateProfileRequest\x1a\x0f.cloud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPREQUEST']._serialized_start=30
  _globals['_SIGNUPREQUEST']._serialized_end=108
  _globals['_LOGINREQUEST']._serialized_start=110
  _globals['_LOGINREQUEST']._serialized_end=157
  _globals['_OTPREQUEST']._serialized_start=159
  _globals['_OTPREQUEST']._serialized_end=199
  _globals['_EMAILREQUEST']._serialized_start=201
  _globals['_EMAILREQUEST']._serialized_end=230
  _globals['_UIDREQUEST']._serialized_start=232
  _globals['_UIDREQUEST']._serialized_end=257
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=259
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=339
  _globals['_RESPONSE']._serialized_start=341
  _globals['_RESPONSE']._serialized_end=367
  _globals['_USERSERVICE']._serialized_start=370
  _globals['_USERSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
